lesson: SpringBoot

spring:
  profiles:
    active: dev




enterprise:
  name: yang
  age: 20
  tel: 13866660000
  subject:
    - java
    - javascript
    - go

---
#开发
server:
  port: 8081
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm_db
    username: root
    password: 123456
---

#测试环境
server:
  port: 8082
spring:
  config:
    activate:
      on-profile: test
---

#生产环境
server:
  port: 8083
spring:
  config:
    activate:
      on-profile: pro
---